/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Command */
        post: operations["command_api_commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replay */
        get: operations["replay_api_replay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Book */
        Book: {
            /** Bids */
            bids: components["schemas"]["Level"][];
            /** Asks */
            asks: components["schemas"]["Level"][];
            /** Orders */
            orders: components["schemas"]["Order"][];
            /** Trades */
            trades: components["schemas"]["Trade"][];
            /** Epoch */
            epoch: number;
        };
        /** Cancel */
        Cancel: {
            /** Request Id */
            request_id: string;
            /**
             * Symbol
             * @enum {string}
             */
            symbol: "AAPL" | "MSFT" | "NVDA" | "DEMO";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "CANCEL";
            /** Order Id */
            order_id: string;
        };
        /** Event */
        Event: {
            /** Seq */
            seq: number;
            /** Command */
            command: components["schemas"]["Limit"] | components["schemas"]["Market"] | components["schemas"]["Cancel"] | components["schemas"]["Replace"] | components["schemas"]["Reset"];
            /** Accepted */
            accepted: boolean;
            /** Error */
            error: string | null;
            /** Trades */
            trades: components["schemas"]["Trade"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Level */
        Level: {
            /** Price Ticks */
            price_ticks: number;
            /** Quantity */
            quantity: number;
            /** Order Count */
            order_count: number;
        };
        /** Limit */
        Limit: {
            /** Request Id */
            request_id: string;
            /**
             * Symbol
             * @enum {string}
             */
            symbol: "AAPL" | "MSFT" | "NVDA" | "DEMO";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "LIMIT";
            /** Order Id */
            order_id: string;
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /** Quantity */
            quantity: number;
            /** Price Ticks */
            price_ticks: number;
        };
        /** Market */
        Market: {
            /** Request Id */
            request_id: string;
            /**
             * Symbol
             * @enum {string}
             */
            symbol: "AAPL" | "MSFT" | "NVDA" | "DEMO";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "MARKET";
            /** Order Id */
            order_id: string;
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /** Quantity */
            quantity: number;
        };
        /** Order */
        Order: {
            /** Order Id */
            order_id: string;
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /**
             * Order Type
             * @enum {string}
             */
            order_type: "LIMIT" | "MARKET";
            /** Quantity */
            quantity: number;
            /** Remaining */
            remaining: number;
            /** Sequence */
            sequence: number;
            /** Price Ticks */
            price_ticks: number | null;
        };
        /** Replace */
        Replace: {
            /** Request Id */
            request_id: string;
            /**
             * Symbol
             * @enum {string}
             */
            symbol: "AAPL" | "MSFT" | "NVDA" | "DEMO";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "REPLACE";
            /** Order Id */
            order_id: string;
            /** Quantity */
            quantity: number;
            /** Price Ticks */
            price_ticks?: number | null;
        };
        /** ReplayResult */
        ReplayResult: {
            /** Verified */
            verified: boolean;
            snapshot: components["schemas"]["Snapshot"];
        };
        /** Reset */
        Reset: {
            /** Request Id */
            request_id: string;
            /**
             * Symbol
             * @enum {string}
             */
            symbol: "AAPL" | "MSFT" | "NVDA" | "DEMO";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "RESET";
        };
        /** Snapshot */
        Snapshot: {
            /** Session Id */
            session_id: string;
            /** Seq */
            seq: number;
            /**
             * Mode
             * @default synthetic simulation
             * @constant
             */
            mode: "synthetic simulation";
            /**
             * Backend
             * @enum {string}
             */
            backend: "python" | "cpp";
            /** Books */
            books: {
                [key: string]: components["schemas"]["Book"];
            };
        };
        /** Trade */
        Trade: {
            /** Sequence */
            sequence: number;
            /**
             * Symbol
             * @enum {string}
             */
            symbol: "AAPL" | "MSFT" | "NVDA" | "DEMO";
            /** Price Ticks */
            price_ticks: number;
            /** Quantity */
            quantity: number;
            /** Maker Order Id */
            maker_order_id: string;
            /** Taker Order Id */
            taker_order_id: string;
            /**
             * Taker Side
             * @enum {string}
             */
            taker_side: "BUY" | "SELL";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    snapshot_api_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    command_api_commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Limit"] | components["schemas"]["Market"] | components["schemas"]["Cancel"] | components["schemas"]["Replace"] | components["schemas"]["Reset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_api_replay_get: {
        parameters: {
            query?: {
                through?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: {
                cursor?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
