/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_research_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_research_runs_get"];
        put?: never;
        /** Start */
        post: operations["start_api_research_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs/{rid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get_api_research_runs__rid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs/{rid}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_research_runs__rid__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs/{rid}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_research_runs__rid__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs/{rid}/artifacts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifact */
        get: operations["artifact_api_research_runs__rid__artifacts__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionEvent */
        ActionEvent: {
            /** Seq */
            seq: number;
            /** Time */
            time: number;
            /** Kind */
            kind: string;
            /** Summary */
            summary: string;
            /** Ok */
            ok?: boolean | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Args */
            args?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Error Type */
            error_type?: string | null;
            /** Model */
            model?: string | null;
            /** Usage */
            usage?: {
                [key: string]: number;
            } | null;
        };
        /** Capabilities */
        Capabilities: {
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Examples */
            examples: string[];
            /** Fixed */
            fixed: {
                [key: string]: unknown;
            };
            /** Limits */
            limits: {
                [key: string]: unknown;
            };
            /** Methods */
            methods: string;
            /** Public Demo */
            public_demo: boolean;
            /** Live Configured */
            live_configured: boolean;
            /** Live Verification */
            live_verification: string;
            /** Tool Schemas */
            tool_schemas: {
                [key: string]: unknown;
            };
        };
        /** ExperimentPlan */
        ExperimentPlan: {
            /** Hypothesis */
            hypothesis: string;
            /**
             * Kind
             * @default simulation
             * @enum {string}
             */
            kind: "simulation" | "matching_benchmark";
            baseline?: components["schemas"]["Parameters"];
            /** Treatments */
            treatments: components["schemas"]["Scenario"][];
            /**
             * Steps
             * @default 500
             */
            steps: number;
            /** Seeds */
            seeds: number[];
            /** Metrics */
            metrics?: ("ending_pnl_ticks" | "max_abs_inventory" | "max_drawdown_ticks" | "execution_edge_pnl_ticks" | "inventory_revaluation_pnl_ticks")[];
            /**
             * Workload
             * @default mixed
             * @enum {string}
             */
            workload: "crossing" | "resting" | "cancel_replace" | "mixed";
            /** Estimated Work */
            estimated_work: number;
            /** Assumptions */
            assumptions: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Limits */
        Limits: {
            /**
             * Max Work
             * @default 40000
             */
            max_work: number;
            /**
             * Max Tools
             * @default 100
             */
            max_tools: number;
            /**
             * Max Model Calls
             * @default 4
             */
            max_model_calls: number;
            /**
             * Max Output Tokens
             * @default 6000
             */
            max_output_tokens: number;
            /**
             * Max Seconds
             * @default 120
             */
            max_seconds: number;
        };
        /** Parameters */
        Parameters: {
            /**
             * Volatility Ticks
             * @default 4
             */
            volatility_ticks: number;
            /**
             * Half Spread Ticks
             * @default 3
             */
            half_spread_ticks: number;
            /**
             * Order Quantity
             * @default 10
             */
            order_quantity: number;
            /**
             * Informed Share
             * @default 0.25
             */
            informed_share: number;
            /**
             * Inventory Skew
             * @default 0.05
             */
            inventory_skew: number;
            /**
             * Max Inventory
             * @default 100
             */
            max_inventory: number;
            /**
             * Quote Refresh Interval
             * @default 1
             */
            quote_refresh_interval: number;
        };
        /** ReviewDecision */
        ReviewDecision: {
            /**
             * Assessment
             * @enum {string}
             */
            assessment: "relevant" | "inconclusive" | "question_mismatch";
            /** Concerns */
            concerns: ("small_sample" | "uncertain_difference" | "multiple_comparisons" | "synthetic_only" | "question_mismatch")[];
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** RunSummary */
        RunSummary: {
            /** Id */
            id: string;
            /** Question */
            question: string;
            /**
             * State
             * @enum {string}
             */
            state: "draft" | "planning" | "validated" | "running" | "reviewing" | "completed" | "failed" | "canceled" | "interrupted";
            /** Created */
            created: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "offline" | "live";
        };
        /** RunView */
        RunView: {
            /** Id */
            id: string;
            /** Audience */
            audience?: "public_demo" | null;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            request: components["schemas"]["StartRequest"];
            /** Source */
            source: {
                [key: string]: unknown;
            };
            /**
             * State
             * @enum {string}
             */
            state: "draft" | "planning" | "validated" | "running" | "reviewing" | "completed" | "failed" | "canceled" | "interrupted";
            plan: components["schemas"]["ExperimentPlan"] | null;
            /** Created */
            created: number;
            /** Elapsed */
            elapsed: number;
            /** Explanation */
            explanation: string;
            /** Completed Tasks */
            completed_tasks: number;
            /** Work */
            work: number;
            /** Tools */
            tools: number;
            /** Model Calls */
            model_calls: number;
            /** Output Reserved */
            output_reserved: number;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /**
             * Usage Complete
             * @default false
             */
            usage_complete: boolean;
            /** Cost Usd */
            cost_usd: number | null;
            /** Cancel Requested */
            cancel_requested: boolean;
            review: components["schemas"]["ReviewDecision"] | null;
            /** Error */
            error: string | null;
            /** Failure Code */
            failure_code?: string | null;
            /** Decision Outcome */
            decision_outcome?: ("planned" | "unsupported" | "clarify") | null;
            /**
             * Resume Count
             * @default 0
             */
            resume_count: number;
            /**
             * Can Resume
             * @default false
             */
            can_resume: boolean;
            /**
             * Next Action
             * @default
             */
            next_action: string;
            /** Events */
            events?: components["schemas"]["ActionEvent"][];
            /** Artifacts */
            artifacts?: string[];
        };
        /** Scenario */
        Scenario: {
            /** Name */
            name: string;
            parameters: components["schemas"]["Parameters"];
        };
        /** StartRequest */
        StartRequest: {
            /** Question */
            question: string;
            /**
             * Mode
             * @default offline
             * @enum {string}
             */
            mode: "offline" | "live";
            /**
             * Workflow
             * @default staged
             * @enum {string}
             */
            workflow: "staged" | "single_agent";
            limits?: components["schemas"]["Limits"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    capabilities_api_research_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    history_api_research_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    start_api_research_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_api_research_runs__rid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_research_runs__rid__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_api_research_runs__rid__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifact_api_research_runs__rid__artifacts__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
